export const IDENTITY_ORGANIZATION_PERMISSIONS = {
  createUser: 'HIDRA_IDENTITY_USERS_EXECUTE',
  evaluatePermission: 'HIDRA_IDENTITY_PERMISSIONS_EXECUTE',
  createOrganizationUnit: 'HIDRA_ORGANIZATION_UNITS_EXECUTE',
  manageEmployees: 'HIDRA_ORGANIZATION_EMPLOYEES_EXECUTE',
} as const;
