export const IDENTITY_ORGANIZATION_PERMISSIONS = {
  createUser: 'identity:users:execute',
  evaluatePermission: 'identity:permissions:execute',
  usersRead: 'identity:users:read',
  rolesRead: 'identity:roles:read',
  permissionsRead: 'identity:permissions:read',
  rolesExecute: 'identity:roles:execute',
  permissionsExecute: 'identity:permissions:execute',
  createOrganizationUnit: 'organization:units:execute',
  manageEmployees: 'organization:employees:execute',
  unitsRead: 'organization:units:read',
  employeesRead: 'organization:employees:read',
  assignmentsRead: 'organization:assignments:read',
  registerOperationalScope: 'organization:operational-scope:register',
  assignResponsibility: 'organization:responsibility:assign',
  revokeResponsibility: 'organization:responsibility:revoke',
} as const;
