export const resources = {
  fr: { translation: {
    auth: {
      basic: { title: 'Connexion de développement', description: 'HidraAPI est configuré en authentification HTTP Basic pour cet environnement. Les identifiants restent uniquement en mémoire dans le navigateur.', username: 'Nom d’utilisateur', password: 'Mot de passe', submit: 'Se connecter', runtime: 'Environnement : {{environment}} · Aucun identifiant n’est intégré au code HidraWeb.' },
      jwt: { title: 'Authentification entreprise requise', description: 'Cet environnement HidraAPI valide des jetons JWT en tant que resource server. HidraWeb n’invente pas de point de connexion local.', contract: 'Le fournisseur d’identité/OIDC remet un access token à AuthProvider, puis HidraWeb recharge le principal courant et les permissions effectives depuis HidraAPI.' },
    },
    permissions: { loading: 'Chargement des autorisations', unavailable: 'Le catalogue d’autorisations HidraAPI ne peut pas être chargé.', failureTitle: 'Métadonnées d’autorisation indisponibles' },
    shell: { sidebar: 'Navigation principale', collapseNavigation: 'Réduire la navigation', expandNavigation: 'Développer la navigation', operationalContextPlaceholder: 'Contexte opérationnel : non sélectionné', searchPlaceholder: 'Recherche globale — à venir', realtimeOffline: 'Temps réel hors ligne', realtimeUnavailable: 'Le transport temps réel sera activé par les tâches métier qui disposent d’événements vérifiés.', language: 'Langue', profile: 'Profil', unknownPrincipal: 'Principal non disponible', authMode: 'Mode d’authentification : {{mode}}', profileUnavailable: 'Profil principal chargé depuis HidraAPI', signOut: 'Se déconnecter', contextDrawer: 'Contexte', closeDrawer: 'Fermer le panneau contextuel' },
    status: { returnOverview: 'Retour à la vue d’ensemble', retry: 'Réessayer', correlation: 'Correlation ID : {{id}}', forbidden: { title: 'Accès refusé', description: 'HidraAPI a refusé cette opération. Le backend reste l’autorité finale pour l’autorisation.' }, notFound: { title: 'Page introuvable', description: 'Cette route HidraWeb ne fait pas partie des espaces opérationnels actuellement implémentés.' } },
    overview: { title: 'Vue d’ensemble', description: 'Socle d’application, authentification et navigation gouvernée par HidraAPI.', shellReady: 'Shell HWEB-002 actif', environment: 'Environnement', authMode: 'Authentification', permissionRoutes: 'Routes publiées', backendModules: 'Modules détectés', catalogOnlyNotice: 'La navigation HidraWeb croise les routes de permission publiées par HidraAPI avec les permissions effectives du principal courant. Les gardes frontend servent l’UX ; HidraAPI reste l’autorité finale.', backendAuthorizationNotice: 'Les gardes frontend utilisent les métadonnées HidraAPI ; le backend conserve l’autorité finale.', principalGapNotice: 'Le shell utilise le principal courant et les permissions effectives exposés par HidraAPI ; le backend reste l’autorité.' },
    workflow: { title: 'Mes tâches', subtitle: 'Boîte de tâches, détail, historique d’instance et actions disponibles calculées par HidraAPI.', executionNotice: 'Les actions affichées sont informatives. Le contrat backend publié ne fournit pas encore d’endpoint d’exécution de transition ; HidraWeb n’en invente aucun.', unavailable: 'Vous ne disposez pas de l’autorisation de lecture des tâches workflow.', inbox: 'Boîte de tâches assignées', loaded: '{{loaded}} tâche(s) chargée(s) sur {{total}}', refresh: 'Actualiser', task: 'Tâche', status: 'Statut', priority: 'Priorité', due: 'Échéance', assignee: 'Assigné à', empty: 'Aucune tâche assignée.', close: 'Fermer', step: 'Étape', sla: 'SLA', availableActions: 'Actions disponibles', noActions: 'Aucune action disponible selon HidraAPI.', instance: 'Instance workflow', timeline: 'Historique', when: 'Date', action: 'Action', actor: 'Acteur', note: 'Note', noTimeline: 'Aucun historique disponible.' },
    nav: { overview: 'Vue d’ensemble', groups: { operations: 'OPÉRATIONS', engineering: 'INGÉNIERIE', intelligence: 'INTELLIGENCE', work: 'TRAVAIL', administration: 'ADMINISTRATION' }, network: 'Réseau', operationsOverview: 'Opérations', alarms: 'Alarmes', events: 'Événements & incidents', planning: 'Planification', integrity: 'Intégrité & maintenance', custody: 'Comptage & custody', risk: 'Risque', analytics: 'Analytique', simulation: 'Simulation', reports: 'Rapports', tasks: 'Mes tâches', notifications: 'Notifications', organization: 'Organisation', identity: 'Identité & accès', configuration: 'Configuration', audit: 'Audit', documents: 'Documents', integrations: 'Intégrations', planned: 'Prévu dans {{task}} — non activé comme espace opérationnel.' },
  } },
  en: { translation: {
    auth: { basic: { title: 'Development sign in', description: 'HidraAPI uses HTTP Basic authentication in this environment. Credentials remain only in browser memory.', username: 'Username', password: 'Password', submit: 'Sign in', runtime: 'Environment: {{environment}} · No credentials are embedded in HidraWeb code.' }, jwt: { title: 'Enterprise authentication required', description: 'This HidraAPI environment validates JWTs as a resource server. HidraWeb does not invent a local login endpoint.', contract: 'The enterprise identity/OIDC integration hands an access token to AuthProvider, then HidraWeb reloads the current principal and effective permissions from HidraAPI.' } },
    permissions: { loading: 'Loading authorization metadata', unavailable: 'HidraAPI permission metadata cannot be loaded.', failureTitle: 'Authorization metadata unavailable' },
    shell: { sidebar: 'Primary navigation', collapseNavigation: 'Collapse navigation', expandNavigation: 'Expand navigation', operationalContextPlaceholder: 'Operational context: not selected', searchPlaceholder: 'Global search — planned', realtimeOffline: 'Realtime offline', realtimeUnavailable: 'Realtime transport is enabled only by business tasks with verified events.', language: 'Language', profile: 'Profile', unknownPrincipal: 'Principal unavailable', authMode: 'Authentication mode: {{mode}}', profileUnavailable: 'Principal profile loaded from HidraAPI', signOut: 'Sign out', contextDrawer: 'Context', closeDrawer: 'Close contextual drawer' },
    status: { returnOverview: 'Return to overview', retry: 'Retry', correlation: 'Correlation ID: {{id}}', forbidden: { title: 'Access denied', description: 'HidraAPI refused this operation. The backend remains the final authorization authority.' }, notFound: { title: 'Page not found', description: 'This HidraWeb route is not part of the currently implemented operational workspaces.' } },
    overview: { title: 'Overview', description: 'Application shell, authentication, and HidraAPI-governed navigation.', shellReady: 'HWEB-002 shell active', environment: 'Environment', authMode: 'Authentication', permissionRoutes: 'Published routes', backendModules: 'Detected modules', catalogOnlyNotice: 'HidraWeb navigation intersects HidraAPI-published permission routes with the current principal's effective permissions. Frontend guards are UX only; HidraAPI remains the final authority.', backendAuthorizationNotice: 'Frontend guards use HidraAPI metadata; backend authorization remains authoritative.', principalGapNotice: 'The shell uses HidraAPI current-principal and effective-permission contracts; the backend remains authoritative.' },
    workflow: { title: 'My Tasks', subtitle: 'Task inbox, task detail, instance history, and HidraAPI-computed available actions.', executionNotice: 'Displayed actions are informational. The published backend contract does not yet expose a transition-execution endpoint, so HidraWeb does not invent one.', unavailable: 'You do not have workflow task read permission.', inbox: 'Assigned task inbox', loaded: '{{loaded}} task(s) loaded of {{total}}', refresh: 'Refresh', task: 'Task', status: 'Status', priority: 'Priority', due: 'Due', assignee: 'Assignee', empty: 'No assigned tasks.', close: 'Close', step: 'Step', sla: 'SLA', availableActions: 'Available actions', noActions: 'No actions are available according to HidraAPI.', instance: 'Workflow instance', timeline: 'Timeline', when: 'When', action: 'Action', actor: 'Actor', note: 'Note', noTimeline: 'No timeline entries are available.' },
    nav: { overview: 'Overview', groups: { operations: 'OPERATIONS', engineering: 'ENGINEERING', intelligence: 'INTELLIGENCE', work: 'WORK', administration: 'ADMINISTRATION' }, network: 'Network', operationsOverview: 'Operations', alarms: 'Alarms', events: 'Events & Incidents', planning: 'Planning', integrity: 'Integrity & Maintenance', custody: 'Metering & Custody', risk: 'Risk', analytics: 'Analytics', simulation: 'Simulation', reports: 'Reports', tasks: 'My Tasks', notifications: 'Notifications', organization: 'Organization', identity: 'Identity & Access', configuration: 'Configuration', audit: 'Audit', documents: 'Documents', integrations: 'Integrations', planned: 'Planned in {{task}} — not enabled as an operational workspace.' },
  } },
  ar: { translation: {
    auth: { basic: { title: 'تسجيل الدخول لبيئة التطوير', description: 'يستخدم HidraAPI مصادقة HTTP Basic في هذه البيئة، وتبقى بيانات الاعتماد في ذاكرة المتصفح فقط.', username: 'اسم المستخدم', password: 'كلمة المرور', submit: 'تسجيل الدخول', runtime: 'البيئة: {{environment}} · لا توجد بيانات اعتماد مضمّنة في كود HidraWeb.' }, jwt: { title: 'مصادقة المؤسسة مطلوبة', description: 'يتحقق HidraAPI من رموز JWT كخادم موارد، ولا ينشئ HidraWeb نقطة دخول محلية غير موجودة.', contract: 'يمرر موفر الهوية/OIDC رمز الوصول إلى AuthProvider، ثم يعيد HidraWeb تحميل هوية المستخدم الحالية والصلاحيات الفعلية من HidraAPI.' } },
    permissions: { loading: 'تحميل بيانات الصلاحيات', unavailable: 'تعذر تحميل بيانات صلاحيات HidraAPI.', failureTitle: 'بيانات الصلاحيات غير متاحة' },
    shell: { sidebar: 'التنقل الرئيسي', collapseNavigation: 'طيّ التنقل', expandNavigation: 'توسيع التنقل', operationalContextPlaceholder: 'السياق التشغيلي: غير محدد', searchPlaceholder: 'البحث العام — مخطط', realtimeOffline: 'الزمن الحقيقي غير متصل', realtimeUnavailable: 'يتم تفعيل النقل اللحظي فقط عند وجود أحداث موثقة من HidraAPI.', language: 'اللغة', profile: 'الملف الشخصي', unknownPrincipal: 'هوية المستخدم غير متاحة', authMode: 'نمط المصادقة: {{mode}}', profileUnavailable: 'ملف المستخدم محمّل من HidraAPI', signOut: 'تسجيل الخروج', contextDrawer: 'السياق', closeDrawer: 'إغلاق لوحة السياق' },
    status: { returnOverview: 'العودة إلى النظرة العامة', retry: 'إعادة المحاولة', correlation: 'معرّف الارتباط: {{id}}', forbidden: { title: 'تم رفض الوصول', description: 'رفض HidraAPI هذه العملية، ويبقى backend المرجع النهائي للصلاحيات.' }, notFound: { title: 'الصفحة غير موجودة', description: 'هذا المسار غير منفذ حاليًا كمساحة تشغيلية في HidraWeb.' } },
    overview: { title: 'نظرة عامة', description: 'هيكل التطبيق والمصادقة والتنقل المحكوم ببيانات HidraAPI.', shellReady: 'هيكل HWEB-002 فعال', environment: 'البيئة', authMode: 'المصادقة', permissionRoutes: 'المسارات المنشورة', backendModules: 'الوحدات المكتشفة', catalogOnlyNotice: 'تتقاطع ملاحة HidraWeb بين مسارات الصلاحيات المنشورة من HidraAPI والصلاحيات الفعلية للمستخدم الحالي. حواجز الواجهة لتحسين تجربة المستخدم فقط، ويبقى HidraAPI المرجع النهائي.', backendAuthorizationNotice: 'تستخدم الواجهة بيانات HidraAPI بينما يبقى backend المرجع النهائي.', principalGapNotice: 'يعتمد الهيكل على عقد المستخدم الحالي والصلاحيات الفعلية في HidraAPI، ويبقى backend المرجع النهائي.' },
    workflow: { title: 'مهامي', subtitle: 'صندوق المهام والتفاصيل وسجل المثيل والإجراءات المتاحة المحسوبة من HidraAPI.', executionNotice: 'الإجراءات المعروضة معلوماتية فقط. العقد المنشور لا يوفّر بعد endpoint لتنفيذ الانتقال، لذلك لا يخترع HidraWeb هذا السلوك.', unavailable: 'لا تملك صلاحية قراءة مهام workflow.', inbox: 'صندوق المهام المسندة', loaded: 'تم تحميل {{loaded}} من {{total}} مهمة', refresh: 'تحديث', task: 'المهمة', status: 'الحالة', priority: 'الأولوية', due: 'الاستحقاق', assignee: 'المكلّف', empty: 'لا توجد مهام مسندة.', close: 'إغلاق', step: 'الخطوة', sla: 'SLA', availableActions: 'الإجراءات المتاحة', noActions: 'لا توجد إجراءات متاحة وفق HidraAPI.', instance: 'مثيل workflow', timeline: 'السجل', when: 'الوقت', action: 'الإجراء', actor: 'الفاعل', note: 'ملاحظة', noTimeline: 'لا توجد عناصر في السجل.' },
    nav: { overview: 'نظرة عامة', groups: { operations: 'العمليات', engineering: 'الهندسة', intelligence: 'التحليلات والذكاء', work: 'العمل', administration: 'الإدارة' }, network: 'الشبكة', operationsOverview: 'العمليات', alarms: 'الإنذارات', events: 'الأحداث والحوادث', planning: 'التخطيط', integrity: 'السلامة والصيانة', custody: 'القياس والتسليم', risk: 'المخاطر', analytics: 'التحليلات', simulation: 'المحاكاة', reports: 'التقارير', tasks: 'مهامي', notifications: 'الإشعارات', organization: 'التنظيم', identity: 'الهوية والوصول', configuration: 'الإعدادات', audit: 'التدقيق', documents: 'الوثائق', integrations: 'التكاملات', planned: 'مخطط ضمن {{task}} — غير مفعل كمساحة تشغيلية.' },
  } },
} as const;
