export const resources = {
  fr: { translation: {
    auth: {
      basic: { title: 'Connexion de développement', description: 'HidraAPI est configuré en authentification HTTP Basic pour cet environnement. Les identifiants restent uniquement en mémoire dans le navigateur.', username: 'Nom d’utilisateur', password: 'Mot de passe', submit: 'Se connecter', runtime: 'Environnement : {{environment}} · Aucun identifiant n’est intégré au code HidraWeb.' },
      jwt: { title: 'Authentification entreprise requise', description: 'Cet environnement HidraAPI valide des jetons JWT en tant que resource server. HidraWeb n’invente pas de point de connexion local.', contract: 'TARGET : le fournisseur d’identité/OIDC doit remettre un access token à AuthProvider. Aucun endpoint principal authentifié n’est actuellement exposé par HidraAPI.' },
    },
    permissions: { loading: 'Chargement des autorisations', unavailable: 'Le catalogue d’autorisations HidraAPI ne peut pas être chargé.', failureTitle: 'Métadonnées d’autorisation indisponibles' },
    shell: { sidebar: 'Navigation principale', collapseNavigation: 'Réduire la navigation', expandNavigation: 'Développer la navigation', operationalContextPlaceholder: 'Contexte opérationnel : non sélectionné', searchPlaceholder: 'Recherche globale — à venir', realtimeOffline: 'Temps réel hors ligne', realtimeUnavailable: 'Le transport temps réel sera activé par les tâches métier qui disposent d’événements vérifiés.', language: 'Langue', profile: 'Profil', unknownPrincipal: 'Principal non disponible', authMode: 'Mode d’authentification : {{mode}}', profileUnavailable: 'Profil principal — contrat backend requis', signOut: 'Se déconnecter', contextDrawer: 'Contexte', closeDrawer: 'Fermer le panneau contextuel' },
    status: { returnOverview: 'Retour à la vue d’ensemble', retry: 'Réessayer', correlation: 'Correlation ID : {{id}}', forbidden: { title: 'Accès refusé', description: 'HidraAPI a refusé cette opération. Le backend reste l’autorité finale pour l’autorisation.' }, notFound: { title: 'Page introuvable', description: 'Cette route HidraWeb ne fait pas partie des espaces opérationnels actuellement implémentés.' } },
    overview: { title: 'Vue d’ensemble', description: 'Socle d’application, authentification et navigation gouvernée par HidraAPI.', shellReady: 'Shell HWEB-002 actif', environment: 'Environnement', authMode: 'Authentification', permissionRoutes: 'Routes publiées', backendModules: 'Modules détectés', catalogOnlyNotice: 'Le catalogue HidraAPI actuel publie des métadonnées de permission dérivées, mais n’expose pas de preuve @PreAuthorize route par route. Les gardes frontend servent donc l’UX ; HidraAPI reste l’unique barrière de sécurité.', backendAuthorizationNotice: 'Les gardes frontend utilisent les métadonnées HidraAPI ; le backend conserve l’autorité finale.', principalGapNotice: 'TARGET backend : aucun endpoint principal authentifié (/me, /principal, whoami) n’a été trouvé dans HidraAPI/main. Le shell affiche uniquement l’identité disponible via le mode d’authentification, sans inventer de profil.' },
    nav: { overview: 'Vue d’ensemble', groups: { operations: 'OPÉRATIONS', engineering: 'INGÉNIERIE', intelligence: 'INTELLIGENCE', work: 'TRAVAIL', administration: 'ADMINISTRATION' }, network: 'Réseau', operationsOverview: 'Opérations', alarms: 'Alarmes', events: 'Événements & incidents', planning: 'Planification', integrity: 'Intégrité & maintenance', custody: 'Comptage & custody', risk: 'Risque', analytics: 'Analytique', simulation: 'Simulation', reports: 'Rapports', tasks: 'Mes tâches', notifications: 'Notifications', organization: 'Organisation', identity: 'Identité & accès', configuration: 'Configuration', audit: 'Audit', documents: 'Documents', integrations: 'Intégrations', planned: 'Prévu dans {{task}} — non activé comme espace opérationnel.' },
  } },
  en: { translation: {
    auth: { basic: { title: 'Development sign in', description: 'HidraAPI uses HTTP Basic authentication in this environment. Credentials remain only in browser memory.', username: 'Username', password: 'Password', submit: 'Sign in', runtime: 'Environment: {{environment}} · No credentials are embedded in HidraWeb code.' }, jwt: { title: 'Enterprise authentication required', description: 'This HidraAPI environment validates JWTs as a resource server. HidraWeb does not invent a local login endpoint.', contract: 'TARGET: the enterprise identity/OIDC integration must hand an access token to AuthProvider. HidraAPI currently exposes no authenticated-principal endpoint.' } },
    permissions: { loading: 'Loading authorization metadata', unavailable: 'HidraAPI permission metadata cannot be loaded.', failureTitle: 'Authorization metadata unavailable' },
    shell: { sidebar: 'Primary navigation', collapseNavigation: 'Collapse navigation', expandNavigation: 'Expand navigation', operationalContextPlaceholder: 'Operational context: not selected', searchPlaceholder: 'Global search — planned', realtimeOffline: 'Realtime offline', realtimeUnavailable: 'Realtime transport is enabled only by business tasks with verified events.', language: 'Language', profile: 'Profile', unknownPrincipal: 'Principal unavailable', authMode: 'Authentication mode: {{mode}}', profileUnavailable: 'Principal profile — backend contract required', signOut: 'Sign out', contextDrawer: 'Context', closeDrawer: 'Close contextual drawer' },
    status: { returnOverview: 'Return to overview', retry: 'Retry', correlation: 'Correlation ID: {{id}}', forbidden: { title: 'Access denied', description: 'HidraAPI refused this operation. The backend remains the final authorization authority.' }, notFound: { title: 'Page not found', description: 'This HidraWeb route is not part of the currently implemented operational workspaces.' } },
    overview: { title: 'Overview', description: 'Application shell, authentication, and HidraAPI-governed navigation.', shellReady: 'HWEB-002 shell active', environment: 'Environment', authMode: 'Authentication', permissionRoutes: 'Published routes', backendModules: 'Detected modules', catalogOnlyNotice: 'The current HidraAPI catalog publishes derived permission metadata but no route-level @PreAuthorize evidence. Frontend guards are UX only; HidraAPI remains the security boundary.', backendAuthorizationNotice: 'Frontend guards use HidraAPI metadata; backend authorization remains authoritative.', principalGapNotice: 'TARGET backend: no authenticated-principal endpoint (/me, /principal, whoami) was found in HidraAPI/main. The shell shows only identity available from the authentication mode and does not invent a profile.' },
    nav: { overview: 'Overview', groups: { operations: 'OPERATIONS', engineering: 'ENGINEERING', intelligence: 'INTELLIGENCE', work: 'WORK', administration: 'ADMINISTRATION' }, network: 'Network', operationsOverview: 'Operations', alarms: 'Alarms', events: 'Events & Incidents', planning: 'Planning', integrity: 'Integrity & Maintenance', custody: 'Metering & Custody', risk: 'Risk', analytics: 'Analytics', simulation: 'Simulation', reports: 'Reports', tasks: 'My Tasks', notifications: 'Notifications', organization: 'Organization', identity: 'Identity & Access', configuration: 'Configuration', audit: 'Audit', documents: 'Documents', integrations: 'Integrations', planned: 'Planned in {{task}} — not enabled as an operational workspace.' },
  } },
  ar: { translation: {
    auth: { basic: { title: 'تسجيل الدخول لبيئة التطوير', description: 'يستخدم HidraAPI مصادقة HTTP Basic في هذه البيئة، وتبقى بيانات الاعتماد في ذاكرة المتصفح فقط.', username: 'اسم المستخدم', password: 'كلمة المرور', submit: 'تسجيل الدخول', runtime: 'البيئة: {{environment}} · لا توجد بيانات اعتماد مضمّنة في كود HidraWeb.' }, jwt: { title: 'مصادقة المؤسسة مطلوبة', description: 'يتحقق HidraAPI من رموز JWT كخادم موارد، ولا ينشئ HidraWeb نقطة دخول محلية غير موجودة.', contract: 'TARGET: يجب أن يمرر موفر الهوية/OIDC رمز الوصول إلى AuthProvider. لا توجد حاليًا نقطة API للمستخدم المصادق عليه.' } },
    permissions: { loading: 'تحميل بيانات الصلاحيات', unavailable: 'تعذر تحميل بيانات صلاحيات HidraAPI.', failureTitle: 'بيانات الصلاحيات غير متاحة' },
    shell: { sidebar: 'التنقل الرئيسي', collapseNavigation: 'طيّ التنقل', expandNavigation: 'توسيع التنقل', operationalContextPlaceholder: 'السياق التشغيلي: غير محدد', searchPlaceholder: 'البحث العام — مخطط', realtimeOffline: 'الزمن الحقيقي غير متصل', realtimeUnavailable: 'يتم تفعيل النقل اللحظي فقط عند وجود أحداث موثقة من HidraAPI.', language: 'اللغة', profile: 'الملف الشخصي', unknownPrincipal: 'هوية المستخدم غير متاحة', authMode: 'نمط المصادقة: {{mode}}', profileUnavailable: 'ملف المستخدم — يتطلب عقد backend', signOut: 'تسجيل الخروج', contextDrawer: 'السياق', closeDrawer: 'إغلاق لوحة السياق' },
    status: { returnOverview: 'العودة إلى النظرة العامة', retry: 'إعادة المحاولة', correlation: 'معرّف الارتباط: {{id}}', forbidden: { title: 'تم رفض الوصول', description: 'رفض HidraAPI هذه العملية، ويبقى backend المرجع النهائي للصلاحيات.' }, notFound: { title: 'الصفحة غير موجودة', description: 'هذا المسار غير منفذ حاليًا كمساحة تشغيلية في HidraWeb.' } },
    overview: { title: 'نظرة عامة', description: 'هيكل التطبيق والمصادقة والتنقل المحكوم ببيانات HidraAPI.', shellReady: 'هيكل HWEB-002 فعال', environment: 'البيئة', authMode: 'المصادقة', permissionRoutes: 'المسارات المنشورة', backendModules: 'الوحدات المكتشفة', catalogOnlyNotice: 'ينشر HidraAPI حاليًا بيانات صلاحيات مشتقة دون دليل @PreAuthorize لكل مسار. حواجز الواجهة لتحسين تجربة المستخدم فقط، ويبقى HidraAPI حاجز الأمان.', backendAuthorizationNotice: 'تستخدم الواجهة بيانات HidraAPI بينما يبقى backend المرجع النهائي.', principalGapNotice: 'TARGET backend: لم يتم العثور على endpoint للمستخدم المصادق عليه في HidraAPI/main. يعرض الهيكل فقط الهوية المتاحة من نمط المصادقة دون اختراع ملف شخصي.' },
    nav: { overview: 'نظرة عامة', groups: { operations: 'العمليات', engineering: 'الهندسة', intelligence: 'التحليلات والذكاء', work: 'العمل', administration: 'الإدارة' }, network: 'الشبكة', operationsOverview: 'العمليات', alarms: 'الإنذارات', events: 'الأحداث والحوادث', planning: 'التخطيط', integrity: 'السلامة والصيانة', custody: 'القياس والتسليم', risk: 'المخاطر', analytics: 'التحليلات', simulation: 'المحاكاة', reports: 'التقارير', tasks: 'مهامي', notifications: 'الإشعارات', organization: 'التنظيم', identity: 'الهوية والوصول', configuration: 'الإعدادات', audit: 'التدقيق', documents: 'الوثائق', integrations: 'التكاملات', planned: 'مخطط ضمن {{task}} — غير مفعل كمساحة تشغيلية.' },
  } },
} as const;
