export const alarmTranslations = {
  fr: {
    title: 'Console des alarmes', subtitle: 'Alarmes actives, historique, détail et actions opérateur gouvernés par HidraAPI.',
    authoritative: 'BACKEND-AUTHORITATIVE', realtimeNotice: 'Les événements temps réel métier ne sont pas encore publiés par HidraAPI. Cette console reste correcte par requêtes et actualisation explicite.',
    suppressionNotice: 'HidraAPI expose désormais la suppression gouvernée des alarmes. HidraWeb envoie uniquement les commandes publiées et ne calcule ni chevauchement, ni restauration, ni expiration côté client.',
    attributionNotice: 'Pour acquittement et clôture, HidraAPI dérive l’identité de l’acteur depuis le principal authentifié. HidraWeb ne permet pas de sélectionner cette identité côté client.',
    unavailable: 'Vous ne disposez pas de l’autorisation de lecture des alarmes.', active: 'Actives', history: 'Historique', refresh: 'Actualiser', filters: 'Filtres', allStates: 'Tous les états', state: 'État', severity: 'Sévérité', topologyAssetId: 'ID actif topologique', from: 'Depuis', to: 'Jusqu’à', apply: 'Appliquer', clear: 'Effacer', loaded: '{{loaded}} alarme(s) chargée(s) sur {{total}}', empty: 'Aucune alarme pour ces critères.', alarm: 'Alarme', priority: 'Priorité', raised: 'Levée le', asset: 'Actif', source: 'Source', open: 'Ouvrir', detail: 'Détail', closePanel: 'Fermer', number: 'Numéro', type: 'Type', firstDetected: 'Première détection', updated: 'Dernière mise à jour', acknowledged: 'Acquittée le', cleared: 'Effacée le', closed: 'Clôturée le', correlation: 'Corrélation', topologyContext: 'Contexte topologique', workflowContext: 'Contexte workflow', openNetwork: 'Ouvrir le réseau', openTasks: 'Ouvrir mes tâches', actions: 'Actions opérateur', executeUnavailable: 'Vous ne disposez pas de l’autorisation d’exécuter les actions d’alarme.', acknowledge: 'Acquitter', organizationUnitId: 'ID unité organisationnelle', organizationUnitCode: 'Code unité', comment: 'Commentaire', closeAlarm: 'Clôturer', closureType: 'Type de clôture', closureReasonId: 'ID motif de clôture', requiresReview: 'Revue workflow requise', reviewWorkflowInstanceId: 'ID instance workflow de revue', shelving: 'Mise en étagère', shelvingHistory: 'Historique de mise en étagère', shelvingReasonId: 'ID motif de mise en étagère', reasonText: 'Motif / commentaire', shelvedUntil: 'Jusqu’au', shelve: 'Mettre en étagère', unshelve: 'Retirer de l’étagère', noShelving: 'Aucun historique de mise en étagère.', suppression: 'Suppression d’alarme', suppressionBackendNotice: 'La politique, l’acteur, les conflits, la restauration et l’expiration restent autoritatifs dans HidraAPI.', suppressionReadUnavailable: 'Vous ne disposez pas de l’autorisation de lire les suppressions.', suppressionExecuteUnavailable: 'Vous ne disposez pas de l’autorisation d’exécuter les suppressions.', suppressionHistory: 'Historique des suppressions', suppressionReasonId: 'ID motif de suppression', suppressedUntil: 'Supprimée jusqu’au', workflowApprovalId: 'ID instance Workflow approuvée', createSuppression: 'Créer la suppression', releaseSuppression: 'Libérer', noSuppressions: 'Aucun historique de suppression pour cette alarme.', openEnded: 'Ouverte', openEndedApprovalNotice: 'Sans date de fin, HidraAPI exige une preuve Workflow approuvée et décide côté serveur.', suppressionSuccess: 'Suppression enregistrée par HidraAPI.', mutationSuccess: 'Opération enregistrée par HidraAPI.', mutationPending: 'Opération en cours…', previous: 'Précédent', next: 'Suivant', page: 'Page {{page}} sur {{totalPages}}', status: 'Statut', when: 'Date', actor: 'Acteur', reason: 'Motif', id: 'ID',
  },
  en: {
    title: 'Alarm Console', subtitle: 'Active alarms, history, detail, and operator actions governed by HidraAPI.',
    authoritative: 'BACKEND-AUTHORITATIVE', realtimeNotice: 'Business realtime events are not yet published by HidraAPI. This console remains correct through queries and explicit refresh.',
    suppressionNotice: 'HidraAPI now exposes governed alarm suppression. HidraWeb sends only published commands and does not calculate overlap, restoration, or expiry on the client.',
    attributionNotice: 'For acknowledgement and closure, HidraAPI derives actor identity from the authenticated principal. HidraWeb does not allow that identity to be selected by the client.',
    unavailable: 'You do not have alarm read permission.', active: 'Active', history: 'History', refresh: 'Refresh', filters: 'Filters', allStates: 'All states', state: 'State', severity: 'Severity', topologyAssetId: 'Topology asset ID', from: 'From', to: 'To', apply: 'Apply', clear: 'Clear', loaded: '{{loaded}} alarm(s) loaded of {{total}}', empty: 'No alarms match these criteria.', alarm: 'Alarm', priority: 'Priority', raised: 'Raised', asset: 'Asset', source: 'Source', open: 'Open', detail: 'Detail', closePanel: 'Close', number: 'Number', type: 'Type', firstDetected: 'First detected', updated: 'Last updated', acknowledged: 'Acknowledged', cleared: 'Cleared', closed: 'Closed', correlation: 'Correlation', topologyContext: 'Topology context', workflowContext: 'Workflow context', openNetwork: 'Open network', openTasks: 'Open my tasks', actions: 'Operator actions', executeUnavailable: 'You do not have permission to execute alarm actions.', acknowledge: 'Acknowledge', organizationUnitId: 'Organization unit ID', organizationUnitCode: 'Unit code', comment: 'Comment', closeAlarm: 'Close alarm', closureType: 'Closure type', closureReasonId: 'Closure reason ID', requiresReview: 'Workflow review required', reviewWorkflowInstanceId: 'Review workflow instance ID', shelving: 'Shelving', shelvingHistory: 'Shelving history', shelvingReasonId: 'Shelving reason ID', reasonText: 'Reason / comment', shelvedUntil: 'Shelved until', shelve: 'Shelve', unshelve: 'Unshelve', noShelving: 'No shelving history.', suppression: 'Alarm suppression', suppressionBackendNotice: 'Policy, actor identity, conflicts, restoration, and expiry remain authoritative in HidraAPI.', suppressionReadUnavailable: 'You do not have suppression read permission.', suppressionExecuteUnavailable: 'You do not have suppression execute permission.', suppressionHistory: 'Suppression history', suppressionReasonId: 'Suppression reason ID', suppressedUntil: 'Suppressed until', workflowApprovalId: 'Approved Workflow instance ID', createSuppression: 'Create suppression', releaseSuppression: 'Release', noSuppressions: 'No suppression history for this alarm.', openEnded: 'Open-ended', openEndedApprovalNotice: 'Without an end time, HidraAPI requires approved Workflow evidence and decides on the server.', suppressionSuccess: 'Suppression recorded by HidraAPI.', mutationSuccess: 'Operation recorded by HidraAPI.', mutationPending: 'Operation in progress…', previous: 'Previous', next: 'Next', page: 'Page {{page}} of {{totalPages}}', status: 'Status', when: 'When', actor: 'Actor', reason: 'Reason', id: 'ID',
  },
  ar: {
    title: 'لوحة الإنذارات', subtitle: 'الإنذارات النشطة والسجل والتفاصيل وإجراءات المشغل المحكومة بواسطة HidraAPI.',
    authoritative: 'BACKEND-AUTHORITATIVE', realtimeNotice: 'لم ينشر HidraAPI بعد أحداث الأعمال اللحظية. تبقى هذه اللوحة صحيحة عبر الاستعلام والتحديث الصريح.',
    suppressionNotice: 'يعرض HidraAPI الآن كبت الإنذارات المحكوم من الخلفية. يرسل HidraWeb الأوامر المنشورة فقط ولا يحسب التداخل أو الاستعادة أو انتهاء الصلاحية على العميل.',
    attributionNotice: 'في الإقرار والإغلاق يشتق HidraAPI هوية الفاعل من المستخدم المصادق عليه، ولا يسمح HidraWeb للعميل باختيار هذه الهوية.',
    unavailable: 'لا تملك صلاحية قراءة الإنذارات.', active: 'النشطة', history: 'السجل', refresh: 'تحديث', filters: 'المرشحات', allStates: 'كل الحالات', state: 'الحالة', severity: 'الخطورة', topologyAssetId: 'معرّف الأصل الطوبولوجي', from: 'من', to: 'إلى', apply: 'تطبيق', clear: 'مسح', loaded: 'تم تحميل {{loaded}} من {{total}} إنذار', empty: 'لا توجد إنذارات مطابقة.', alarm: 'الإنذار', priority: 'الأولوية', raised: 'وقت الرفع', asset: 'الأصل', source: 'المصدر', open: 'فتح', detail: 'التفاصيل', closePanel: 'إغلاق', number: 'الرقم', type: 'النوع', firstDetected: 'أول اكتشاف', updated: 'آخر تحديث', acknowledged: 'وقت الإقرار', cleared: 'وقت الإزالة', closed: 'وقت الإغلاق', correlation: 'الارتباط', topologyContext: 'السياق الطوبولوجي', workflowContext: 'سياق سير العمل', openNetwork: 'فتح الشبكة', openTasks: 'فتح مهامي', actions: 'إجراءات المشغل', executeUnavailable: 'لا تملك صلاحية تنفيذ إجراءات الإنذار.', acknowledge: 'إقرار', organizationUnitId: 'معرّف الوحدة التنظيمية', organizationUnitCode: 'رمز الوحدة', comment: 'تعليق', closeAlarm: 'إغلاق الإنذار', closureType: 'نوع الإغلاق', closureReasonId: 'معرّف سبب الإغلاق', requiresReview: 'مراجعة سير العمل مطلوبة', reviewWorkflowInstanceId: 'معرّف مثيل سير عمل المراجعة', shelving: 'التعليق المؤقت', shelvingHistory: 'سجل التعليق المؤقت', shelvingReasonId: 'معرّف سبب التعليق', reasonText: 'السبب / التعليق', shelvedUntil: 'معلق حتى', shelve: 'تعليق', unshelve: 'إلغاء التعليق', noShelving: 'لا يوجد سجل تعليق.', suppression: 'كبت الإنذار', suppressionBackendNotice: 'تبقى السياسة وهوية الفاعل والتعارضات والاستعادة والانتهاء خاضعة لـ HidraAPI.', suppressionReadUnavailable: 'لا تملك صلاحية قراءة عمليات الكبت.', suppressionExecuteUnavailable: 'لا تملك صلاحية تنفيذ عمليات الكبت.', suppressionHistory: 'سجل الكبت', suppressionReasonId: 'معرّف سبب الكبت', suppressedUntil: 'مكبوت حتى', workflowApprovalId: 'معرّف مثيل Workflow الموافق عليه', createSuppression: 'إنشاء الكبت', releaseSuppression: 'تحرير الكبت', noSuppressions: 'لا يوجد سجل كبت لهذا الإنذار.', openEnded: 'مفتوح المدة', openEndedApprovalNotice: 'عند عدم تحديد وقت نهاية، يطلب HidraAPI دليل Workflow معتمد ويتخذ القرار على الخادم.', suppressionSuccess: 'سجل HidraAPI عملية الكبت.', mutationSuccess: 'سجل HidraAPI العملية.', mutationPending: 'العملية قيد التنفيذ…', previous: 'السابق', next: 'التالي', page: 'الصفحة {{page}} من {{totalPages}}', status: 'الحالة', when: 'الوقت', actor: 'الفاعل', reason: 'السبب', id: 'المعرّف',
  },
} as const;
