export const alarmTranslations = {
  fr: {
    title: 'Console des alarmes', subtitle: 'Alarmes actives, historique, détail et actions opérateur gouvernés par HidraAPI.',
    authoritative: 'BACKEND-AUTHORITATIVE', realtimeNotice: 'Les événements temps réel métier ne sont pas encore publiés par HidraAPI. Cette console reste correcte par requêtes et actualisation explicite.',
    suppressionNotice: 'Aucune opération de suppression d’alarme n’est exposée par le contrat backend accepté ; HidraWeb n’invente donc aucun contrôle de suppression.',
    attributionNotice: 'Pour acquittement et clôture, le contrat backend actuel reçoit la référence acteur depuis le client. Cette attribution n’est pas présentée comme une identité serveur dérivée.',
    unavailable: 'Vous ne disposez pas de l’autorisation de lecture des alarmes.', active: 'Actives', history: 'Historique', refresh: 'Actualiser', filters: 'Filtres', allStates: 'Tous les états', state: 'État', severity: 'Sévérité', topologyAssetId: 'ID actif topologique', from: 'Depuis', to: 'Jusqu’à', apply: 'Appliquer', clear: 'Effacer', loaded: '{{loaded}} alarme(s) chargée(s) sur {{total}}', empty: 'Aucune alarme pour ces critères.', alarm: 'Alarme', priority: 'Priorité', raised: 'Levée le', asset: 'Actif', source: 'Source', open: 'Ouvrir', detail: 'Détail', closePanel: 'Fermer', number: 'Numéro', type: 'Type', firstDetected: 'Première détection', updated: 'Dernière mise à jour', acknowledged: 'Acquittée le', cleared: 'Effacée le', closed: 'Clôturée le', correlation: 'Corrélation', topologyContext: 'Contexte topologique', workflowContext: 'Contexte workflow', openNetwork: 'Ouvrir le réseau', openTasks: 'Ouvrir mes tâches', actions: 'Actions opérateur', executeUnavailable: 'Vous ne disposez pas de l’autorisation d’exécuter les actions d’alarme.', acknowledge: 'Acquitter', actorId: 'Référence acteur', actorDisplayName: 'Nom acteur', organizationUnitId: 'ID unité organisationnelle', organizationUnitCode: 'Code unité', comment: 'Commentaire', closeAlarm: 'Clôturer', closureType: 'Type de clôture', closureReasonId: 'ID motif de clôture', requiresReview: 'Revue workflow requise', reviewWorkflowInstanceId: 'ID instance workflow de revue', shelving: 'Mise en étagère', shelvingHistory: 'Historique de mise en étagère', shelvingReasonId: 'ID motif de mise en étagère', reasonText: 'Motif / commentaire', shelvedUntil: 'Jusqu’au', shelve: 'Mettre en étagère', unshelve: 'Retirer de l’étagère', noShelving: 'Aucun historique de mise en étagère.', mutationSuccess: 'Opération enregistrée par HidraAPI.', mutationPending: 'Opération en cours…', previous: 'Précédent', next: 'Suivant', page: 'Page {{page}} sur {{totalPages}}', status: 'Statut', when: 'Date', actor: 'Acteur', reason: 'Motif', id: 'ID',
  },
  en: {
    title: 'Alarm Console', subtitle: 'Active alarms, history, detail, and operator actions governed by HidraAPI.',
    authoritative: 'BACKEND-AUTHORITATIVE', realtimeNotice: 'Business realtime events are not yet published by HidraAPI. This console remains correct through queries and explicit refresh.',
    suppressionNotice: 'No alarm suppression operation is exposed by the accepted backend contract, so HidraWeb does not invent suppression controls.',
    attributionNotice: 'For acknowledgement and closure, the current backend contract receives the actor reference from the client. This is not presented as server-derived identity.',
    unavailable: 'You do not have alarm read permission.', active: 'Active', history: 'History', refresh: 'Refresh', filters: 'Filters', allStates: 'All states', state: 'State', severity: 'Severity', topologyAssetId: 'Topology asset ID', from: 'From', to: 'To', apply: 'Apply', clear: 'Clear', loaded: '{{loaded}} alarm(s) loaded of {{total}}', empty: 'No alarms match these criteria.', alarm: 'Alarm', priority: 'Priority', raised: 'Raised', asset: 'Asset', source: 'Source', open: 'Open', detail: 'Detail', closePanel: 'Close', number: 'Number', type: 'Type', firstDetected: 'First detected', updated: 'Last updated', acknowledged: 'Acknowledged', cleared: 'Cleared', closed: 'Closed', correlation: 'Correlation', topologyContext: 'Topology context', workflowContext: 'Workflow context', openNetwork: 'Open network', openTasks: 'Open my tasks', actions: 'Operator actions', executeUnavailable: 'You do not have permission to execute alarm actions.', acknowledge: 'Acknowledge', actorId: 'Actor reference', actorDisplayName: 'Actor display name', organizationUnitId: 'Organization unit ID', organizationUnitCode: 'Unit code', comment: 'Comment', closeAlarm: 'Close alarm', closureType: 'Closure type', closureReasonId: 'Closure reason ID', requiresReview: 'Workflow review required', reviewWorkflowInstanceId: 'Review workflow instance ID', shelving: 'Shelving', shelvingHistory: 'Shelving history', shelvingReasonId: 'Shelving reason ID', reasonText: 'Reason / comment', shelvedUntil: 'Shelved until', shelve: 'Shelve', unshelve: 'Unshelve', noShelving: 'No shelving history.', mutationSuccess: 'Operation recorded by HidraAPI.', mutationPending: 'Operation in progress…', previous: 'Previous', next: 'Next', page: 'Page {{page}} of {{totalPages}}', status: 'Status', when: 'When', actor: 'Actor', reason: 'Reason', id: 'ID',
  },
  ar: {
    title: 'لوحة الإنذارات', subtitle: 'الإنذارات النشطة والسجل والتفاصيل وإجراءات المشغل المحكومة بواسطة HidraAPI.',
    authoritative: 'BACKEND-AUTHORITATIVE', realtimeNotice: 'لم ينشر HidraAPI بعد أحداث الأعمال اللحظية. تبقى هذه اللوحة صحيحة عبر الاستعلام والتحديث الصريح.',
    suppressionNotice: 'لا يعرض العقد الخلفي المقبول عملية لكبت الإنذار، لذلك لا ينشئ HidraWeb عناصر تحكم غير موجودة.',
    attributionNotice: 'في الإقرار والإغلاق يستقبل العقد الخلفي الحالي مرجع الفاعل من العميل، ولا يتم تقديمه كهوية مشتقة من الخادم.',
    unavailable: 'لا تملك صلاحية قراءة الإنذارات.', active: 'النشطة', history: 'السجل', refresh: 'تحديث', filters: 'المرشحات', allStates: 'كل الحالات', state: 'الحالة', severity: 'الخطورة', topologyAssetId: 'معرّف الأصل الطوبولوجي', from: 'من', to: 'إلى', apply: 'تطبيق', clear: 'مسح', loaded: 'تم تحميل {{loaded}} من {{total}} إنذار', empty: 'لا توجد إنذارات مطابقة.', alarm: 'الإنذار', priority: 'الأولوية', raised: 'وقت الرفع', asset: 'الأصل', source: 'المصدر', open: 'فتح', detail: 'التفاصيل', closePanel: 'إغلاق', number: 'الرقم', type: 'النوع', firstDetected: 'أول اكتشاف', updated: 'آخر تحديث', acknowledged: 'وقت الإقرار', cleared: 'وقت الإزالة', closed: 'وقت الإغلاق', correlation: 'الارتباط', topologyContext: 'السياق الطوبولوجي', workflowContext: 'سياق سير العمل', openNetwork: 'فتح الشبكة', openTasks: 'فتح مهامي', actions: 'إجراءات المشغل', executeUnavailable: 'لا تملك صلاحية تنفيذ إجراءات الإنذار.', acknowledge: 'إقرار', actorId: 'مرجع الفاعل', actorDisplayName: 'اسم الفاعل', organizationUnitId: 'معرّف الوحدة التنظيمية', organizationUnitCode: 'رمز الوحدة', comment: 'تعليق', closeAlarm: 'إغلاق الإنذار', closureType: 'نوع الإغلاق', closureReasonId: 'معرّف سبب الإغلاق', requiresReview: 'مراجعة سير العمل مطلوبة', reviewWorkflowInstanceId: 'معرّف مثيل سير عمل المراجعة', shelving: 'التعليق المؤقت', shelvingHistory: 'سجل التعليق المؤقت', shelvingReasonId: 'معرّف سبب التعليق', reasonText: 'السبب / التعليق', shelvedUntil: 'معلق حتى', shelve: 'تعليق', unshelve: 'إلغاء التعليق', noShelving: 'لا يوجد سجل تعليق.', mutationSuccess: 'سجل HidraAPI العملية.', mutationPending: 'العملية قيد التنفيذ…', previous: 'السابق', next: 'التالي', page: 'الصفحة {{page}} من {{totalPages}}', status: 'الحالة', when: 'الوقت', actor: 'الفاعل', reason: 'السبب', id: 'المعرّف',
  },
} as const;
